#!/usr/bin/env python
# author: N037 D4w3

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-u', '--user', required=True,
        help="CERN username")
args = parser.parse_args()

from toolman import packages

packages.fetch(args.user)
